AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront for Photo Sharing App Frontend

Parameters:
  EnvironmentName:
    Type: String
    Default: photo-share
  FrontendBucketName:
    Type: String
    Default: photo-share-frontend-789613278086-ap-northeast-1
  FrontendBucketWebsiteURL:
    Type: String
    Default: http://photo-share-frontend-789613278086-ap-northeast-1.s3-website-ap-northeast-1.amazonaws.com

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Select [2, !Split ["/", !Ref FrontendBucketWebsiteURL]]
            Id: FrontendOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: FrontendOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD, OPTIONS]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: PriceClass_200

Outputs:
  DistributionId:
    Value: !Ref CloudFrontDistribution
  DistributionDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
